### ISSUE TITLE
[Improvement] [UX] Automaticial builds for multiple Systems per schedule

### ISSUE THREAD

**Issue by zDEFz** [kroyee/SpeedBlocks#10]
Hi,

i don't know how it works but it is possible to set up a schedule for building for different systems automaticially.
http://buildbot.net/

It also makes a upload of the succesful build.

Think it could make things easier for us - to make changes and request a new build.

**Comment by kb1900** [comment]
https://docs.buildbot.net/current/tutorial/firstrun.html#goal

they have quite an indept tutorial

**Comment by kroyee** [comment]
I'm looking a bit at the tutorial but I'm failing to grasp exactly what it is supposed to do.
My first impression is that this is for very big projects with different parts having alot of different dependencies.
If you find a way to make it useful I would obviously have no problems with that.

**Comment by zDEFz** [comment]
My thought that it could look like this http://buildbot.orphis.net/
Maybe the task is to much effort - but it would be convenient if we can request a build and just have to upload the files that are changed.

I don't know if that buildbot orphis is only custom code or not. However i think it can work.

**Comment by chinatsu** [comment]
My opinion on this is that an automatic build system is a bit large scale for something as (relatively) small as this is at the moment. I think it's better to aim for somewhat regular releases of "official" binaries only when milestones have been made and a version bump has occurred. GitHub has a releases page, actually: https://github.com/kroyee/SpeedBlocks/releases

Here's some additional information on that: https://help.github.com/articles/creating-releases/

**Comment by kb1900** [comment]
Yeah I think the release of "official" binaries with a numerical build version number would be good. 

Commits can be merged to developmental builds and then every so often can be deployed as the "official up to date binary"

**Comment by kroyee** [comment]
This sounds good to me. As soon as we have tested a bit of multiplayer I will make a first release, then make a developer branch that we can work with.
