### ISSUE TITLE
[FN] We can't disable sound / audio

### ISSUE THREAD

**Issue by zDEFz** [kroyee/SpeedBlocks#15]
**Steps to reproduce**

1. Start with the latest build
2. Disable Audio (uncheck) 
3. Quit the game / press video apply button for save

**Expected result**

Audio is disabled

**Actual result**

Audio is enabled

https://www.youtube.com/watch?v=Oro3uAijsuY
Binarys https://drive.google.com/open?id=0B7DljHrC1lQHdkNnVzR1TDFlR0E

**Comment by kroyee** [comment]
You still don't have to press the video apply to save anything. It saves. :smile: 
Will make sure countdown sounds in multiplayer don't play if you have sound disabled.

**Comment by zDEFz** [comment]
So it will play in training despite being disabled?

**Comment by kroyee** [comment]
No, It should not play anything if disabled. Something is a bit wrong.
Just pointing out that the apply button in video options will not change anything (other then video options).

**Comment by kroyee** [comment]
I was getting irregular result here... but I can't find anything wrong in the code.
I tried to make a clean build and I think it's working as it should now.
