### ISSUE TITLE
[FN] Crash / Strange behavior of the UI while playing online / going back

### ISSUE THREAD

**Issue by zDEFz** [kroyee/SpeedBlocks#18]
**Steps to reproduce**

1. Start the game and put 83.254.154.180 in the Server IP
2. Choose no name and enter some mode - leave reenter another , play a bit
3. disconnect and login as user now
4. choose some lobby / leave

Note: Latest build is done - i did clean and completely rebuild it.

**Expected result**

No crash (did not happen the second time now)
UI is robust.

**Actual result**

At first it crashed, second it gives me no option to play anymore...

**URL**

https://youtu.be/w2lWPt8GaIc

**Comment by kroyee** [comment]
That was the server crashing. I'm not sure what happened but it reported errors trying to send TCP packets.
