### ISSUE TITLE
Execution failes on Linux

### ISSUE THREAD

**Issue by Noir-** [kroyee/SpeedBlocks#2]
Hi!

I managed to successfully build the executable with the following steps:

Cloning my fork
> `git clone https://github.com/Noir-/SpeedBlocks.git`

Grabbing, extracting SFML
> `http://www.sfml-dev.org/files/SFML-2.4.2-linux-gcc-64-bit.tar.gz && tar xf SFML-2.4.2-linux-gcc-64-bit.tar.gz`

Grabbing, extracting Boost (This step is not really reproducible because of fucked up URL and filename)
> `wget https://downloads.sourceforge.net/project/boost/boost/1.63.0/boost_1_63_0.tar.bz2?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fboost%2F%3Fsource%3Dtyp_redirect&ts=1489832574&use_mirror=netcologne boost_1_63_1.tar.bz2 && tar xf boost_1_63_0.tar.bz2\?r\=https\:%2F%2Fsourceforge.net%2Fprojects%2Fboost%2F\?source\=typ_redirect boost_1_63_0.tar.bz2`

Grabbing, extracting TGUI
> `https://github.com/texus/TGUI/archive/0.7.3.zip && unzip 0.7.3.zip`

Building TGUI
> `env SFML_ROOT=../SFML-2.4.2 cmake ./`

Then I modified the Makefile to fix includes and linking like this (Quick & dirty search & replace):
https://gist.github.com/Noir-/636890e01646a8a485920ecacc88c9ab

Building succeeds.

As last step I added the shared library locations to `LD_LIBRARY_PATH`
`LD_LIBRARY_PATH="TGUI-0.7.3/lib/;SFML-2.4.2/lib/" && export LD_LIBRARY_PATH`

Now when I try `./sfml` i get the following error:

> loadOptions failed, setting default options
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted (core dumped)

Before I start digging deeper into this issue I just wanted to know if I did anything wrong.

______________________
Here are some system specs just in case:

>`uname -a`
>Linux noir-workstation 4.4.49-16-default SMP Sun Feb 19 17:40:35 UTC 2017 (70e9954) x86_64 x86_64 x86_64 GNU/Linux

> `g++ -v`
> Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/4.8/lto-wrapper
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,objc,fortran,obj-c++,java,ada --enable-checking=release --with-gxx-include-dir=/usr/include/c++/4.8 --enable-ssp --disable-libssp --disable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --disable-libgcj --disable-libmudflap --with-slibdir=/lib64 --with-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --enable-linker-build-id --enable-linux-futex --program-suffix=-4.8 --without-system-libunwind --with-arch-32=i586 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 4.8.5 (SUSE Linux)`

**Comment by kroyee** [comment]
Regex is implemented in gcc from version 4.9.0 an forward. Try updating gcc/g++.
See [this post](http://stackoverflow.com/questions/12530406/is-gcc-4-8-or-earlier-buggy-about-regular-expressions) for more info.

**Comment by Noir-** [comment]
Thanks, I'll try this!

**Comment by Noir-** [comment]
I installed GCC 5:

> `gcc-5 --version`

> gcc-5 (SUSE Linux) 5.3.1 20160301 [gcc-5-branch revision 233849]
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Now I'm getting a segmentation fault after the window pops up shortly :/

**Comment by kroyee** [comment]
Did you rebuild the libraries after upgrade?
If you did maybe one of SFMLs dependencies using regex could be causing problems? This seems unlikely though. Just speculating.
Run a debugger like gdb and see if you can get some info on where the segfault is.

**Comment by Noir-** [comment]
May I ask you which exact environment and configuration you are using for development? Which GCC version? How are the vendor libraries involved into the build process? Are they installed into the system? Which linux distro you are using?

**Comment by kroyee** [comment]
> uname -a
> Linux super-chrome 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

> g++ -v
> Using built-in specs.
> COLLECT_GCC=g++
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1\~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 

I have SFML built from the package manager.
Version 2.3.2+dfsg-1 (wow... I was pretty sure I was running 2.4.2)

TGUI built from the 0.7 master git rep, probably not the latest one atm but fairly fresh.

boost also from the package manager.

**Comment by kroyee** [comment]
Make sure all the old .o files where removed in the speedblocks folder.
`rm *.o`

**Comment by Noir-** [comment]
I actually added a clear target in the Makefile. I also improved some other stuff. I'll create a pull request when it's stable.

Here's the current GDB output with all relevant debug symbols installed:

> ~/projects/SpeedBlocks> gdb ./sfml 
GNU gdb (GDB; openSUSE Leap 42.2) 7.11.1
This GDB was configured as "x86_64-suse-linux".
Reading symbols from ./sfml...done.
(gdb) run
Starting program: /home/noir/projects/SpeedBlocks/sfml 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffec034700 (LWP 5407)]
[New Thread 0x7fffec034700 (LWP 5408)]
[Thread 0x7fffec034700 (LWP 5407) exited]
[New Thread 0x7ffff7f11700 (LWP 5409)]
loadOptions failed, setting default options

> Thread 1 "sfml" received signal SIGSEGV, Segmentation fault.
0x00007ffff6c220aa in std::local_Rb_tree_decrement (__x=0x148b3c0) at ../../../../../libstdc++-v3/src/c++98/tree.cc:98
98      ../../../../../libstdc++-v3/src/c++98/tree.cc: No such file or directory.
Missing separate debuginfos, use: zypper install libbz2-1-debuginfo-1.0.6-37.82.x86_64 libdbus-1-3-debuginfo-1.10.12-2.1.x86_64
(gdb) 

I think the missing symbols are not relevant at the moment. I'll investigate and keep you updated.

**Comment by chinatsu** [comment]
I got it to compile and run on Arch Linux, although I had to jump through a few hoops..

I tested with @Noir- 's fork.

The libraries were downloaded (mostly) through my package manager.
`pacman -S boost SFML`

TGUI was acquired through [the AUR](https://aur.archlinux.org/packages/tgui-git/)

I had to add `-lstdc++ -lm` to the end of the sfml entry in the Makefile to satisfy the compiler with the right libraries.

Then it complained about libharfbuzz, which has apparently broken a package *kind of* recently, and adding `-lharfbuzz` did not solve it for me. Following [these steps](https://www.reddit.com/r/archlinux/comments/5mphpu/psa_harfbuzz_update_infinality_breaking_system/dc7fvzf/) to recompile harfbuzz solved my issue. After this, it compiles and runs.

Please note, I may already have had some libraries necessary to compile this installed.

**Comment by Noir-** [comment]
That's weird, compilation was pretty straight forward to me but running is not.

According to [this stacktrace](https://gist.github.com/Noir-/2d5420d3bf33d4d468bc495bf9a78b5b), the error comes from the TGUI lib.

I suspect some kind of dependency compatibility problem. Maybe I should try the older SFML version? For me, static linking the libs looks like a good idea.

**Comment by texus** [comment]
The only thing that I can think of for that stacktrace is some incompatibility, although I never faced something like that on linux. Make certain that SFML, TGUI and SpeedBlocks are all compiled with the same compiler.
The program builds and starts fine here on Arch Linux without having to modify anything. Edit: With @Noir- 's fork I do had to manually add `-lstdc++ -lm` like @chinatsu said.

On linux you typically don't link static, unless you know what you are doing that is going to make things even more complex.

**Comment by Noir-** [comment]
Well, I didn't compiled SFML - I downloaded it precompiled. I'll try that.

**Comment by texus** [comment]
I found why I need to include "-lstdc++" in your fork. The CC variable is set to the C compiler, not the c++ one (it is already defined so the makefile does now overwrite it with g++ since you use ?=). You should use the CXX variable instead. Maybe this is related to your problem.

**Comment by Noir-** [comment]
I'm sorry, this was a bug I already fixed but not pushed to the repo yet. The reason I introduced this was because I needed to overwrite the hardcoded `g++` with `g++-5` from my distro. There I confused CC with CXX but always overwritten the correct variable since I actively used it.

Now I built SFML from the source but I'm running in the same error.
I think I will move the whole development to a Ubuntu VM with a configuration similar to kroyees'.

**Comment by kroyee** [comment]
I went ahead and built SFML-2.4.2 from source today.

- Installed all SFML dependencies lib-dev
- Built SFML
- Rebuilt TGUI

I ran into [this Ubuntu 16.04 issue](http://en.sfml-dev.org/forums/index.php?topic=20638.0), after patch it works as expected.

**Comment by Noir-** [comment]
@kroyee Could you provide a Linux binary which I can try to run on my system? I'm curious whether this will work. If it does, maybe I'll make a binary diff and look at strace and such.

**Comment by texus** [comment]
Maybe you should try building with clang instead of gcc and see if that makes a difference.
You could also try building sfml and tgui in debug mode so that you have a bit more information in the stacktrace.

**Comment by texus** [comment]
@Noir- This issue is definately just on your pc and setup. I was really interested in finding the cause of the crash because unlike on windows I haven't seen a crash on linux yet due to some incompatibility (except in libraries like glib). And the fact that the stacktrace lead to inside TGUI code made me even more curious. But I can't reproduce it here when installing openSUSE Leap 42.2.

I followed the following steps to successfully install and run it. The main difference that I see with your steps is the installation of boost.
```
sudo zypper install gcc5 gcc5-c++ git cmake sfml2-devel Mesa-libGL-devel boost_1_61-devel
git clone https://github.com/texus/TGUI
cd TGUI
cmake -DCMAKE_C_COMPILER=gcc-5 -DCMAKE_CXX_COMPILER=g++-5 .
make -j4
sudo make install
cd ..
git clone https://github.com/kroyee/SpeedBlocks
cd SpeedBlocks/
sed -i "s/g++/g++-5/g" Makefile 
make -j4
./sfml
```

If installing the dependencies like that doesn't solve it then it probably isn't worth it to continue to search the issue.

**Comment by kroyee** [comment]
Will send over a binary as soon as I get home, 1-2 hours from now.

**Comment by kroyee** [comment]
Binary is [here](https://drive.google.com/open?id=0B1UCzPzcZfFvYVJ5Z0EwNHhDTXM).
Is there a way for me to share it via GitHub? Gist seems to only take text/code.

**Comment by chinatsu** [comment]
Yes, through the [Releases](https://github.com/kroyee/SpeedBlocks/releases) tab

**Comment by Noir-** [comment]
It's working now! I tried what texus wrote. I'm trying to backtrack where the exact error was. It feels like this might be important in the future to make the game as portable as possible on Linux.
