### ISSUE TITLE
[FN][Network] Timeout not working for non responding adresses

### ISSUE THREAD

**Issue by zDEFz** [kroyee/SpeedBlocks#25]
**Steps to reproduce**

1. Enter for example 1.2.3.4 as IP adress
2. Click on Join

**Expected result**

Game gives a message that we was unable to connect

**Actual result**

Game hangs

Code that is probably affected ( debugged it )
sf::Socket::Status status = tcpSock.connect(serverAdd, tcpPort); will retry forever

network.cpp

>  sf::Socket::Status network::connect() {
> 	tcpSock.setBlocking(true);
> 	sf::Socket::Status status = tcpSock.connect(serverAdd, tcpPort);
> 	tcpSock.setBlocking(false);
> 	return status;
> }
>

**Comment by zDEFz** [comment]
https://youtu.be/wqGoppK2Y4k

**Comment by kroyee** [comment]
It should be using the OS default timeout. Witch is probably very high.
Might need to give it a more humane set timeout.

**Comment by kroyee** [comment]
@zDEFz could you confirm if this works now? Should be a 5 second timeout, and you should be able to see the "connecting..." screen while waiting.

I don't know cause mine was not having that problem to start with.
