### ISSUE TITLE
[Discussion] Public Beta milestone

### ISSUE THREAD

**Issue by Noir-** [kroyee/SpeedBlocks#27]
I suggest that a first milestone named "public beta" or something like 0.1b1 is created.

What does @kroyee want to see in it? What do others think? Please create a separate issue and reference it here if things go very detailed. 

IMO:
The goal could be to provide executables for every platform and giving users some possibilities to provide feedback. I would not even want a ranking or a forum in 0.1b1 (As kroyee mentioned in the ToDo list).
In my opinion both are rather complex features. A ranking needs a database, a algorithm, user accounts etc. Especially the user account feature might be a tough decision (Do we want to end like Cultris 2 where the whole game is tied to a shitty CMS?). A forum is also not really needed at this point since it needs some grade of moderation. (Do we really want 674893 threads like "cann u plz impl3ment tspin?????? thx") Of course we need feedback and bug reports and I have a idea how we can handle feedback which I elaborate here #28 .

**Comment by kroyee** [comment]
This sounds like a good milestone to me. Executables and feedback.
I would also like to see the server being on a somewhat stable place.

As for the ranking system, we can implement it once we know more how we want to do it.
I've initiated #29 for more in-depth discussion about that.

**Comment by kroyee** [comment]
What is a shitty CMS? :confused:
I have more or less assumed that a dedicated server running both the game-server and a webhost/database setup would be ideal, but this is not really my area of expertise.

**Comment by Noir-** [comment]
With the shitty CMS I meant this MoJo Portal software which handles the whole Cultris 2 Website. It was never meant to be a community software so it has almost no community functionality. I guess the Cultris 2 team never thought that their game would be so successful so is seems that they closely coupled the game server with this portal which ended in the current state which we all hate so much. :laughing: 

I draw a very quick, dirty and incomplete diagram about what is on my mind regarding server architecture. I attached it to this post.
![speedblocks_deployment](https://cloud.githubusercontent.com/assets/6486186/24158055/7f4da798-0e5b-11e7-89d2-e16b8bfc0f73.png)

**Comment by ghost** [comment]
Nice Diagram! Very easy to understand and follow.

**Comment by kroyee** [comment]
Alright, this looks nice.
In my simple testing solutions I had the backend auth the client via HTTP-post to the web-server. This might have some security issues though?
It seemed to work well (as long as the webserver actually responded!!!).

**Comment by Noir-** [comment]
I created a new issue #31 for the architecture thing.
