### ISSUE TITLE
[Discussion] [UX] Minimalist in-game bug reporting 

### ISSUE THREAD

**Issue by Noir-** [kroyee/SpeedBlocks#28]
I have the following idea to give users the opportunity to report bugs.

There could be a "Report" button in the bottom corner of the game which is always visible. If the user clicks on it, a dialog would open where are a few text fields and labels like:

> Please report in Swedish, English or German. We can not handle your report otherwise. Alternatively you can open an issue here [github link]
>1. Tell us what happened
>2. What did you expected to happen instead?
>3. What do we need to do to see what you are seeing?
>4. How can we contact you when we have questions?

This message could be posted to a simple backend with a database (this is coded in a short time, I'd do that) where we (or some of us) can read it back through a simple HTML interface. We could then manually create an Issue when its relevant. Of course it could use the Github API for automatic issue creation but this could lead to a lot of low quality issues in the repo here.

What do you think?

Advanced possible features:
- Hook this reporting into crash handlers
- Automatically collect and append some technical data about the game state and the target system

**Comment by kroyee** [comment]
This sounds like a great feature.
I can take care of making the GUI implementation. Should it send the info to the game-server or will it be directly sent from the client?

As for crash handling, I don't really know how to go about doing that so I might not be much help initially.

**Comment by Noir-** [comment]
It could be a good idea to let the server send the data to the reporting API. This could reduce the trouble when the reporting API is changed since no client code is affected and needs to be redistributed.

When it comes to crash handling and in depth technical recording, we might go better with a library for that. But this feature looks minimalist enough to implement it by ourselves.

**Comment by kroyee** [comment]
The front half is in place.
I tested and it works well, but you need to be connected to the server to send it...
If not it tells "You need to be connected to the server to send a bug report"

**Comment by Noir-** [comment]
That's a good point... Maybe we should go back to posting the content directly to the reporting API? I'll start working on the server part this evening. How does the client request looks like?

**Comment by kroyee** [comment]
the client request?
Right now the information is just stored in 4 strings, happened, expected, reproduce, contact.

**Comment by kroyee** [comment]
It looks like [this](http://imgur.com/a/f6lgH).
Just realised not the whole sentences are included at the bottom. :hankey:

**Comment by zDEFz** [comment]
@kroyee please add a function to contact via mail but without to open any mail program.
Because what can you report if a server is down?
You don't necessarily need a setted up Mail. And you can dump the Stack trace to a file and next time we open the game it should show a message ( It seems a crash occurred, do you want to sent it to the developer?" And the option to add additional info.

**Comment by kroyee** [comment]
If you know how to do that, it would be a great addition!

**Comment by Noir-** [comment]
How can we implement sending a mail from the client without much overhead or leaving credentials somewhere? Also, most mails which are sent directly from a consumer IP (Not via SMTP or such) are blocked on most mail servers because most of them are spam. That's also a reason why I came up with the extra backend idea. Maybe we should remove the hop over the game server and HTTP POST it directly to the reporting backend.

**Comment by kroyee** [comment]
Yes, I think that would work better.

**Comment by zDEFz** [comment]
**1.** 

- You send your report to a simple Database that is read only - containing credentials for the place you want connect to. 

- You use for example using credentials from a [Anonymouse] Github Account.
Then you call the API and raise the issue here. This will do for [Debug] Builds.
We don't have to include it for [Release] Builds.

- You fill another database with issues or files that have a cronjob that sends you an e-mail.
But i think this just would be inefficient.
We can do it another way. Database doesn't need to have read only. We simply can report 


**2.**

I would recommend Firebase https://firebase.google.com/
We can have a free Account :)**
 
- **It can specialize for improving quality - would need to further investigate but it should be easy to implement.**

https://firebase.google.com/docs/cpp/setup
https://firebase.google.com/docs/web/setup 

It's Cross-Platform

Personally i like the second option most.  :)

**Comment by Noir-** [comment]
You might overestimate the effort of building a simple HTTP API which accepts 5 post parameters which are stored in a database. I can do this in little time using PHP (or maybe another language for the lulz) and a modern (micro) framework. I also own a server where I can host this. Sending HTTPS requests is also easy on the client side and it's very likely to be needed in the future anyway. The worst thing that can happen is, that someone reverse engineers this API from the source code and starts spamming us which is very unlikely to happen in the near future.

For me there's no reason for giving any data to Google.

**Comment by zDEFz** [comment]
Was your answer referring to the **first** recommendation or the **second**?
In any case i got told firebase is simple to use and implement.

**Edit**

About Google - they will have the data anyways so i don't care to much personally.

What would be your thought on how we should do it @Noir-  ?

**Comment by Noir-** [comment]
My plan is a simple web app which accepts a request like this:

> POST /api/client/error HTTP/1.1
> Host: speedblocks.org/api/error
> Content-Type: application/x-www-form-urlencoded
> Cache-Control: no-cache
>happening=my+cat+always+farts+when+i+send+lines+to+my+opponent&supposed=sppedblocks+should+not+affect+the+behavior+of+my+cat&reproduce=1.+get+a+cat+(mine+is+a+male+munchkin+cat)+2.+open+speed+blocks+3.+join+multiplayer+mode+and+start+playing+in+a+room&contact=ilovemuchkin%40somepsychiatry.com

This is processed (maybe filtered) by the app and stored in a database. Then I build a simple web interface which reads the submitted reports back and displays them. I think this interface should be only accessible by a few developers (htaccess is sufficient I guess) since there are email addresses or other sensitive information.

When we encourage users to send information to us, especially the contact information, we have the responsibility to take care of it. And dumping it in a Google database is not the exact definition of this in my opinion.

**Comment by kroyee** [comment]
SFML does not support HTTPS.
Can we pass the information on to some other application on the same machine, and do HTTPS from there or is additional library needed to accomplish this? (like OpenSSL)

**Comment by Noir-** [comment]
> SFML does not support HTTPS.

OMG! We absolutely need HTTPS. We are passing sensitive information over the wire. (Not only user contact information but also username/passwords in the future with the account feature)
We can use CURL for example (Which is using OpenSSL on Linux AFAIK) It's written in C but [C++ wrappers are around](https://curl.haxx.se/libcurl/bindings.html). Other libraries can be found [here](https://curl.haxx.se/libcurl/competitors.html).

**Comment by zDEFz** [comment]
But still we want a simple server mode i guess - just in case ...

Can we still host the server by ourself ? There should be a mode where i can use the Server without a forum or a registered user. 
Like  - if we need to much stuff to host it by ourself in future that should be easy like it is now i think..

HTTPS needs a SSL certificate right?

**Comment by Noir-** [comment]
I'm already preparing a server for the script including a SSL certificate (LetsEncrypt to the rescue). There will be no authentication or something. We'll see how it will work. For DNS I'm using a dynamic DNS provider for now.

**Comment by Noir-** [comment]
My backend is up and running! It's reachable under https://speedblocks.spdns.org/bugs It's a first draft which accepts a post request which contains JSON like the following:

>POST /bugs HTTP/1.1
>Host: speedblocks.spdns.org
>Content-Type: application/json
>Cache-Control: no-cache

>{"happening":"my cat always farts when i send lines to my opponent", "supposed":"speedblocks should not affect the behavior of my cat", "reproduce":"1. get a cat (mine is a male munchkin cat) 2. open speed blocks 3. join multiplayer mode and start playing in a room", "contact":"wtf@omg.com"}

Or try it with cURL like:

> curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H -d '{"happening":"my cat always farts when i send lines to my opponent", "supposed":"speedblocks should not affect the behavior of my cat", "reproduce":"1. get a cat (mine is a male munchkin cat) 2. open speed blocks 3. join multiplayer mode and start playing in a room", "contact":"wtf@omg.com"}' "https://speedblocks.spdns.org/bugs"

You can then request all bugs with

> curl -X GET -H "Content-Type: application/json" -H "Cache-Control: no-cache" "https://speedblocks.spdns.org/bugs"

HTTPS is required. No authentication yet. No GUI yet. Char limit is 1000 which should be enough.

**Comment by kroyee** [comment]
I tried to sen the post in like
`happening=thestuffthathappened&supposed=itwassupposedtowork`
and so on and got back
`{"happening":["The happening field is required."],"supposed":["The supposed field is required."],"reproduce":["The reproduce field is required."],"contact":["The contact field is required."]}`
So I'm assuming the syntax is wrong.

**Comment by kroyee** [comment]
Oh, wait.
I did a normal HTTP-post... dang. Opened up what I thought was a HTTPS example.

**Comment by Noir-** [comment]
Please note that I'm only accepting JSON structured like in the examples.

**Comment by kroyee** [comment]
Can't get it to take the bloody string...
maybe a typo somewhere. it's a bit messy with all the " inside the string. :smiley: 
are the [ supposed to be in the string?
finding examples both with and without.

**Comment by Noir-** [comment]
Ok it seems like you never worked with JSON before. Lets go through my example string step by step. 

>{

A valid JSON object is always encapsulated in these brackets. But you will find many parsers which will accept  square brackets `[]` too. But this is a convenience function and in no standard AFAIK.

>"happening":"my cat always farts when i send lines to my opponent"

This is a key-value pair. Each key must be enclosed with double quotes `"`.  Single quotes `'` are not valid. You might find examples without with the following reason: JSON is derived from the way how objects are notated in JavaScript but there are syntactical differences. One of them is, that the keys don't need to be enclosed with `"`. So the situation is: JSON always is a valid JavaScript object but a valid JavaScript object is not always a valid JSON object. The value needs to be enclosed with `"` only when it is a string. String is one of four primitives in JSON. There are also bool (`true`,`false`), integer and float. These must not be enclosed with `"` if they should be recognized as these type by the parser.

>,

Key-value pairs are separated with a colon `,` mostly to make them easier to read/parse. The last key-value pair in a block must not have a trailing `,`. 

That's it with my example.

You are also confused by the server response so I'll elaborate on the details.

> "happening":["The happening field is required."]

Here you can see a slightly different key-value pair. The value is actually an array with only one member. The reason of this is that I'm doing some validation on the server side. When the validation fails, the errors regarding each key will be shown to the client. There is the possibility that there's more than one problem with the value so the message is always encapsulated in an array to make the data structure more consistent. This is mostly automatically done by the framework I'm using. (Laravel Lumen)

I hope things are more clear now. You can find a JSON validator here: http://jsonlint.com/

**Comment by Noir-** [comment]
I also suggest that you are using a library for parsing and generating JSON since it's the de-facto standard in modern API communication.

**Comment by Noir-** [comment]
Update: I added a bullshitty bootstrap GUI for viewing bugs. You can access it here: https://speedblocks.spdns.org/bugs/view The data is just dummy stuff which a library created for me. The buttons on the right are not working yet. They are supposed to delete the bug or forward it to our issue tracker.

**Comment by kroyee** [comment]
So this is what I'm doing.
```
void UI::sendReport(sf::String happened, sf::String expected, sf::String reproduce, sf::String contact, tgui::ChildWindow::Ptr win) {
	CURL *curl;
	CURLcode res;

	/* In windows, this will init the winsock stuff */ 
	curl_global_init(CURL_GLOBAL_ALL);

	/* get a curl handle */ 
	curl = curl_easy_init();
	if(curl) {
		/* First set the URL that is about to receive our POST. This URL can
		just as well be a https:// URL if that is what should receive the
		data. */ 
		struct curl_slist *headers = NULL;
		headers = curl_slist_append(headers, "Accept: application/json");
		headers = curl_slist_append(headers, "Content-Type: application/json");
		headers = curl_slist_append(headers, "charsets: utf-8");

		curl_easy_setopt(curl, CURLOPT_URL, "https://speedblocks.spdns.org/bugs");
		curl_easy_setopt(curl, CURLOPT_HTTPHEADER, headers);
		/* Now specify the POST data */ 
		sf::String postfield = "{\"happening\": \"" + happened + "\", \"supposed\": \"" + expected + "\", \"reproduce\": \"" + reproduce + "\", \"contact\": \"" + contact + "\" }";
		cout << postfield.toAnsiString().c_str() << endl;
		curl_easy_setopt(curl, CURLOPT_POSTFIELDS, postfield.toAnsiString().c_str());
		/* Perform the request, res will get the return code */ 
		res = curl_easy_perform(curl);
		/* Check for errors */ 
		if(res != CURLE_OK)
			fprintf(stderr, "curl_easy_perform() failed: %s\n",
		curl_easy_strerror(res));

		/* always cleanup */ 
		curl_easy_cleanup(curl);
	}
	else
		cout << "Curl failed to load" << endl;
	curl_global_cleanup();
	win->destroy();
}
```

the use of sf::String is just because that's the object I'm getting from the GUI, then i do a 2way conversion with .toAnsiString().c_str()

the test output of the string looks like
`{"happening": "this", "supposed": "is", "reproduce": "a", "contact": "munchkin example" }`

**Comment by Noir-** [comment]
Okay this looks good on the first glace. But it's not working? Is this code in the repo yet? If not, could you create a feature branch for this?

**Comment by kroyee** [comment]
Created topic-branch curl

I think it is actually working. I was confused by the fact that
`{"happening":["The happening field is required."],"supposed":["The supposed field is required."],"reproduce":["The reproduce field is required."],"contact":["The contact field is required."]}`
seems to be return at the end from the server no matter what input it gets.

**Comment by kroyee** [comment]
If i do

> curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -H -d '{"happening":"my cat always farts when i send lines to my opponent", "supposed":"speedblocks should not affect the behavior of my cat", "reproduce":"1. get a cat (mine is a male munchkin cat) 2. open speed blocks 3. join multiplayer mode and start playing in a room", "contact":"wtf@omg.com"}' "https://speedblocks.spdns.org/bugs"

i get back

> [1/4]: "happening":"my cat always farts when i send lines to my opponent" --> <stdout>
> --_curl_--"happening":"my cat always farts when i send lines to my opponent"
> curl: (6) Could not resolve host: "happening"
> 
> [2/4]:  "supposed":"speedblocks should not affect the behavior of my cat" --> <stdout>
> --_curl_-- "supposed":"speedblocks should not affect the behavior of my cat"
> curl: (6) Could not resolve host:  "supposed"
> 
> [3/4]:  "reproduce":"1. get a cat (mine is a male munchkin cat) 2. open speed blocks 3. join multiplayer mode and start playing in a room" --> <stdout>
> --_curl_-- "reproduce":"1. get a cat (mine is a male munchkin cat) 2. open speed blocks 3. join multiplayer mode and start playing in a room"
> curl: (6) Could not resolve host:  "reproduce"
> 
> [4/4]:  "contact":"wtf@omg.com" --> <stdout>
> --_curl_-- "contact":"wtf@omg.com"
> curl: (6) Could not resolve host: omg.com"
> {"happening":["The happening field is required."],"supposed":["The supposed field is required."],"reproduce":["The reproduce field is required."],"contact":["The contact field is required."]}

**Comment by Noir-** [comment]
Okay seems like there's something wrong with the command. I also discovered a bug on the server side. I trying to fix this at the moment...

**Comment by Noir-** [comment]
Okay the curl command had little bug: There was a malformed parameter which resulted in this behavior.

> ... -H "Cache-Control: no-cache" **-H** -d  ....'

If you remove the one `-H` everything is working fine. My backend is working properly btw.

**Comment by kroyee** [comment]
Ok, good.
I'm still not able to find a combination of heasers/options to make it accept the post. Not sure what I'm missing. The only difference I can see in the examples from what I'm doing is that they are sending to http:// and I'm trying to do it to https://

**Comment by Noir-** [comment]
Do you talking about C++ code or command line? I'll checkout the branch...

**Comment by kroyee** [comment]
I got it now!
The problem was in how I passed along the c-type string. Had to make a std::strcpy before I passed it on to the curl function. Will update the topic branch.

**Comment by zDEFz** [comment]
Hi, it's bit cut off
Third text option in-game.

https://i.imgur.com/JtvrAm4.png

**Edit** do you see the end of that screenshot? It looks for me like there was intended for more text

**Comment by Noir-** [comment]
OT: Why are you using external image/video/file hoster when GitHub can do the same?

**Comment by zDEFz** [comment]
@Noir- because it's 1 click for me. Choosing the portion of monitor and it does already upload it and copy the url to my clipboard

**Comment by kroyee** [comment]
Yes, will take care of that when I move the code into the master branch.
I have not done that yet because it would require adding 1 additional library (libcurl) to the project for HTTPS support.

**The current form does not send any report, it's just a prototype.**

I was thinking to wait until we do the first beta release, so tester don't have to bother with that before. Don't know if that's good or not though, maybe should just move it in right away?

**Comment by Noir-** [comment]
I created a public repository for my backend: https://github.com/Noir-/SB-Bug-API
Issues regarding this backend should be discussed there. Therefore I'll close this issue.
