### ISSUE TITLE
[Discussion] Ranking system

### ISSUE THREAD

**Issue by kroyee** [kroyee/SpeedBlocks#29]
My ideas for the ranking system is to make something similar to Hearthstone, it works like this:

All players start with a ranking of 25. Every game the player gets an adjustment to his/hes points depending on performance. If the player reaches 1000 points, rank goes down by 1. If the player reaches -1000 points, rank goes up by one (not higher then 25). In both cases points are reset to 0.

For each rank gained the amounts of points gained or lost is modified by a factor of 0.x to effectively make the span longer between higher rank. Climbing from 1 to 0 requires 5 times the amount of points then climbing from 25 to 24, the same goes for falling back down to 2.

When a player reaches 0, they get Hero rank. Once you reach Hero rank you can not fall back down to 1. In addition to this you also get access to a Hero room where you can play against other player of Hero rank. Here ELO is implemented (or something else) to determine an exact ranking between the players.

The first day of the month, the ranking would reset and give way for a new monthly season.
The result from each season would then be used to give you a rating for the whole year, and possibly a lifetime span aswell.

I have made an algorithm for the first stage, ranking from 25 to 0, and ran it through some simple simulations to adjust it a bit. It's not very well commented, but you can see it [here](https://gist.github.com/kroyee/af2aa2603f8c397fa1f313200b032100).

I could also note that a player of Hero ranking can still play with everyone else, but he would then be treated as a guest. Meaning that he would not gain or loose any points and his position would be irrelevant to the other players points adjustments.

That's my idea.

**Comment by ghost** [comment]
"The first day of the month, the ranking would reset and give way for a new monthly season.
_The result from each season would then be used to give you a rating for the whole year_, and possibly a lifetime span aswell."
I really think this is similar to League's ranking system which is simple but to the point and focuses on current skill more than anything else. I like that aspect for the most part and hope it works out with a smaller user base. [https://boosteria.org/wp-content/uploads/ranked-percentage-season3.jpg](url)

**Comment by Noir-** [comment]
Very fundamental question: Do we want ranking for games of more than two parties? (Teams or Players) The Cultris 2 forums are full of critique against all ranking systems which were implemented because they were buggy or flawed. Well... maybe it was just because Simon was to busy changing things. But we can learn from that that it's not easy to implement.

And it's also obvious that a 1 vs 1 ranking would drastically simplify things. At least there would be the option to set the focus on 1 vs 1 ranking first before we move on to more complicated things.

**Comment by kroyee** [comment]
I think a ranking-system for FFA would be great, but it need to be much less rigid then what Cultris is using. You can focus a ranking system on different aspect. It seems to me that having a spot on accurate rating is not the most important thing. More important would be to make it fun and that people see the result of their playing.
You can get to the top without having to grind for ages, but equally the people who show results month after month should stand out in some way aswell.

1vs1 ranking on the other hand could very well be more focused on being accurate.

**Comment by kb1900** [comment]
I think this is a fantastic approach and something c2 sorely lacks. 1v1 should be all about pecking order and climbing the ranks **longitudinally**

ffa on the other hand should be much more variably and less static
