### ISSUE TITLE
[TN] FrameRate incorrect under Windows

### ISSUE THREAD

**Issue by zDEFz** [kroyee/SpeedBlocks#3]
**Steps to reproduce:**

1. Set Framerate to 300
2. Set Frametime to 1000

Expected Result:

Frame Rate is 300

Actual Result:

Frame Rate is 333
--------------------

1. Set Framerate to 600
2. Set Frametime to 1000

Expected Result:

Frame Time is 600

Actual Result:

Frame Rate is 999
--------------------

**Comment by kb1900** [comment]
+1 here for this issue.  exact same results

**Comment by kroyee** [comment]
Does this mean you got it running? That's good news!
The time measuring system is not exact so setting it to 300 and getting 333 seems reasonable.
In the second example is it framerate or frametime your measuring?

**Comment by kroyee** [comment]
To clarify. How it currently works is that the screen is draw according to framerate interval but input in processed every frametime, in this case every 1ms.

**Comment by zDEFz** [comment]
@kroyee i used an build made without visual studio 2015.
Still an issue. Please stick to the gewaltig.net topic :)

Its naturally framerate. It was some typo :/

**Comment by kroyee** [comment]
999 is very far of. This is likely due to float to int trunc. Will change the calculation.

**Comment by kroyee** [comment]
This has been updated, please verify with the new build before I close the issue.

**Comment by chinatsu** [comment]
Having frame time set to 1000, I am able to set frame rates accurately up to around 1500 FPS, where it seems like my computer won't give me any more. 

I'm not sure if VSync behaves as normal, though; enabling it also gives me ~1500 FPS. My monitor is set to 60Hz at the moment.

**Comment by kroyee** [comment]
Ok, that is good.
The VSync is built in to the SFML library. Not sure why that would not work. It does work on my computer.
