### ISSUE TITLE
[Discussion] Combo Timer length

### ISSUE THREAD

**Issue by kb1900** [kroyee/SpeedBlocks#32]
So I am unsure if you wish the combo timer to be unique to SpeedBlocks and different from C2 but this is something I thought worth bringing up.

In Cultris 2, when you are mid-combo, blocks that you place that FAIL to clear a line will SUBTRACT combo time remaining from your timer (In addition to the time it takes to drop that place). I think that the time subtracted is higher proportional to how large your combo count is at -- i.e. more time is subtracted for this mistake at a 7 combo than a 3 combo.

So for example, I'm at a 3 combo with 4 seconds left on my timer. I place a piece without clearing a line. Then I have 3.5 seconds left on my timer (.2 seconds to place the piece and .3 seconds subtracted as a penalty for not clearing the line). These numbers are random but I hope my point about this nuance of the timer system from C2 is understood.

Right now it is very simple/easy to achieve 20+ combos because of how "static" the combo timer is. There is no added penalty for failing to clear lines and "building" your stack as long as you clear lines at a certain interval.

**Comment by kb1900** [comment]
Please comment if I am completely wrong or if this would be a worthwhile consideration for SpeedBlocks

**Comment by kb1900** [comment]
This also might be better understood in Okey_Dokey's post on this thread (post no. 2): http://gewaltig.net/Forums/Thread.aspx?pageid=1&mid=5&ItemID=1&thread=902&postid=7547

**Comment by kroyee** [comment]
There is currently a penalty for not clearing during combo, but it's quite small (0,2 seconds) and it's static.
I have not really made any decitions about how it "should" be, I figure we need to start playing and trying to see what works best.

I do however like the idea of having a more linear combotimer. As Cultris works it get exponentially harder to get higher and higher combo, and it also gives exponentially more reward for each step. I think this is good as it very clearly rewards higher combos.

I do however think that having a curve that doesn't top out at around 11-12-13 is better because the interval of a pretty good combo to a very good combo is often just 1 piece, and that 1 piece makes all the difference.

If you have the same aproach, but the topping out comes higher, and at the same time the reward does not increase as fast you would have a wider span of "very good" results.

This is not to say that +20 combos is in any way ideal. But the general approach of keeping the exponetial growth, but making the curve a bit smoother appeals to me.

**Comment by kb1900** [comment]
Yes - i think its very much a "balancing" between the range of "good combos" (which in c2 right now are only really 8,9,10+ in the mid game. with 11+ being hard to achieve) and the achievement of "record-worthy" first-combos (12, 13, 14 etc.)

I 100% agree that a wider span of "very good" combos is something important for the game. But I also believe that the reward of high "first-combos" should be exponential (to what degree, I'm not sure)

**Comment by kb1900** [comment]
Referencing commit: af8817878239e93faab9d4fc0e0743e3a78189f5 which changed the combo timer and the lines sent.
--
I believe the lines sent is far too high. I believe that there should be some chance that, in a 1v1

IF:
Player 1 sends a somewhat large combo (14-16 or so in the current set up seems very easy)
Player 2 messes up and sends a poor combo (maybe only a 10 or double 6's)

Player 2 **should** have the ability to downstack efficiently through the garbage and survive. 

--
In the current system, this scenario is only resolved by Player 2 if they send large combos while downstacking, before/while the garbage is appearing on their screen. This is okay, but for how many lines are sent, it is almost impossible - you are almost better off just having a messy field and scrambling for a 10 combo to block the incoming lines rather than downstacking efficiently and clearing your playfield.

I hope this makes sense. TLDR: right now, downstacking efficiently is not rewarded as much as simply comboing messily when trying to survive - this is due to too many lines being sent and blocking with combos becoming more important than downstacking well

**Comment by kroyee** [comment]
To send a combo will never block any lines in the current system. Only the lines cleared can block incoming lines. Clearing 2 lines will block one, clearing 3 lines will block 2, clearing 4 lines will bock 3. Maybe this should be changed?

So to block with a combo have absolutely no effect at the moment. You will however send more lines to your opponent and by doing that you might be forcing him to block/downstack.

I might very well be that the amount of lines sent are too high. I compared a bit with cultris yesterday on the [wiki](https://harddrop.com/wiki/Cultris_II) and speedblock send quite alot less lines then what cultris does if those numbers are accurate.
A 12 combo will send ~37 compared to cultris 53, and a 14 will send 53 compared to 75.
Seeing how much easier it is to get a high combo this might need to be reduced more still. Or to make it harder to reach high combos.

I don't feel like I've had the chance to play enough to really have a good feeling for it. Hopefully more people can add some feedback here.

**Comment by zDEFz** [comment]
For my case: A 19 combo is what i can reach with a full stack + some additonal ds.

**Comment by kroyee** [comment]
I'm guessing that was before I adjusted the system though?

**Comment by zDEFz** [comment]
The 25 Combo by z2 sam was the very first build.

On latest i manage to get a 19 combo. 21 combo or higher is even harder.

**Comment by kroyee** [comment]
a 19 would currently send 117 lines... so yeah. We probably need to decrease the time gained even more.

**Comment by kb1900** [comment]
Yes that is what I meant @kroyee - i definitely misunderstood some mechanics but was just attempting to describe my "feel" of the game. 

i like that in c2, even if my opponent does a 10 combo mid game, i can still survive fairly well if i downstack well. in this game with 17,18,19 combos happening so often, there is a lot of "insta death" even if you have a strong downstack.

**Comment by kb1900** [comment]
currently when downstacking - at 150bpm i am able to make a 15 combo each time with minimal conscious effort. this is because i can simply clear lines fast enough that i will have a full combo timer while i am already at 11 or so.

eveen if i dont stack high, just clearing lines at the bottom at around 150 bpm will net me minimum 11 combo and on average 13 combo. i think this makes speed a little over powered. i cant imagine what a 180 bpm player will send just by clearing lines at the bottom. no need for stacking at all.

**Comment by rmcat** [comment]
I haven't had a c chance to play online, but I think if we want the game to be back and forth like Cultris, blocking combos should work similarly. Cancelling only 1, 2 and 3 lines for doubles, triples and tetrises respectively is much too little.

I've created a new branch with some adjustments to the combo system. Would be good to get feedback on it. Combos around 12 are not too difficult. It can be further tweaked.

**Comment by kroyee** [comment]
Yes, you are probably very right about the blocking. Just had not thought about how it works in cultris tbh.
I had a chance to play for a bit the other day and winning with 40-50 lines incoming was not all that unusual. Will change this right away.
