### ISSUE TITLE
[TN] Editing the Network Field lets the App hang each time

### ISSUE THREAD

**Issue by zDEFz** [kroyee/SpeedBlocks#33]
**Steps to reproduce**

Open Game - Remove some characters up to 127.0

**Expected result**

No hang

**Actual result**

hangs each time

https://www.youtube.com/watch?v=V2QKFtVN4a0

**Comment by kroyee** [comment]
Is it possible to see in the debugger where the hang occurs?

**Comment by zDEFz** [comment]
I will debug it now

**Comment by kroyee** [comment]
It's really strange, because the only code that runs when you edit the field is this:
```
void UI::changeServerAdd(sf::String addr) {
	net->serverAdd = addr.toAnsiString();
}
```
Why that would cause a hickup like that I don't know.
It does not happen on my machine. Does @kb1900 have the same behavior?

**Comment by zDEFz** [comment]
angsthas3 has the problem reported to me and i did reproduce it!

Ok found the issue!

> Each time the field gets changed it calls a TextChanged event!
> It should be only be a mere Text field which is being submitted afterwards.
> If you remove after 127.0 it does need two removements to reach 127.

**Comment by kb1900** [comment]
yes i have the same behavior @kroyee  and it looks like @zDEFz pinpointed it exactly :)

**Comment by zDEFz** [comment]
The Network field still hangs.
Select all the text in the field, rename -> small hang there

But besides this the old bug got fixed.
Running latest build.

**Comment by jefgenowitsch** [comment]
I can confirm the small hang DEF describes

**Comment by zDEFz** [comment]
seems fixed

**Comment by jefgenowitsch** [comment]
I'm using the latest build and it seems that the issue is happening again.
zDEFz thinks, that it was overwritten with a merge?
Btw. the Combo Timer issue #45 is also affected.
