### ISSUE TITLE
[TN] The data in the Scoreboard isn't aligned correctly

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#34]
The data in the Scoreboard isn't aligned correctly in the columns

**Comment by kroyee** [comment]
please attach a screenshot

**Comment by zDEFz** [comment]
https://i.imgur.com/XnjDef3.png

You forgot to use columns it looks like mere tabulator tabs which are different regarding the username

**Comment by kroyee** [comment]
Just update to the latest client, this was reworked earlier today.
