### ISSUE TITLE
[UX] Auto AFK for single Player doesn't work

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#38]
Auto AFK for single Player doesn't work

**Comment by Noir-** [comment]
Do you mean the training? Please edit your issue with some more description like you did in other issues.

**Comment by zDEFz** [comment]
He means probably that if you play ffa for example you go to auto afk if you do nothing.

**Comment by kroyee** [comment]
Commited an update for this, missed to reference.
