### ISSUE TITLE
[UX] Game should automaticially restart after Gameover Screen

### ISSUE THREAD

**Issue by zDEFz** [kroyee/SpeedBlocks#4]
**Steps to reproduce:**

1. Lose
2. Observe

**Expected result:**

Game restarts 

**Actual Result**

Another Game can be started with Enter

**Comment by kb1900** [comment]
Perhaps add a element (button) to start next round/new game and an element to toggle autostart()

**Comment by kroyee** [comment]
How is this expected result? This could be easily changed to restart automatically after a time interval if so desired.

**Comment by zDEFz** [comment]
@kroyee It's just feedback so we know what we should fix / what is desired.

**Comment by kb1900** [comment]
@kroyee i think expected in the sense that the user would not know to press enter to restart. this is more like feature request than real issue

**Comment by zDEFz** [comment]
Because of that its marked as UX (User Experience).

**Comment by kroyee** [comment]
Noted. It's all good.
Keep the feedback flowing!

**Comment by kroyee** [comment]
The game now tells you to press enter to restart it.
I will close this issue for now.
