### ISSUE TITLE
[UX]Behavior of the chat history

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#41]
**Steps to repoduce:**
Login and then write something in the chat and relogin again. 

**Expected result** (when manually logged off)
The history of the chat was cleared.

**Actual result**  (when manually logged off)
The historical chat is still shown in the chat

For Discussion:
Maybe having the chat not cleared under certain cirqumstances isn't that bad.
For example after a disconnection.

Idea:
Having the chat cleared when the user does a relogin after a certain amount of time.

**Comment by kroyee** [comment]
I think having the chat not cleared under all circumstances seems good. If you disconnect to change some settings, and come back you still have the chat there.
Maybe we could just insert lines saying:
-- Yout left the chat --
-- You rejoined the chat --

If you join a different room it should probably clear though. It doesn't do that atm.
