### ISSUE TITLE
[BUG] Strange Data in the Score field

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#42]
https://youtu.be/eqcxKxs6XBQ

M.C.E's name is "Uknown" in the statistics and also his BPM is awesome!

**Comment by kroyee** [comment]
His playfield is also only grey pieces.
Did this happen only once?
Is it reproducable?
Was the client/server up to date?

**Comment by kb1900** [comment]
i can reproduce this bug every time i connect to the test server. in fact, i can not get the score field to ever display more than 1 player's correct statistics. I always have multiple entries for "Unnkown" 
with a 3xxx or 4xxx bpm and other nonsensical entries for the rest of the statistics in those rows. The single correct entry that is always present is always the highest row in the score table.

**Comment by jefgenowitsch** [comment]
I think he changed the colour of his pieces to white?
I will try to reproduce it.
The client/server were up to date.

**Comment by kroyee** [comment]
Even if he changed his colors, your client would use your colors to display his pieces. So there is something that's not right with how the packets between the server and client are being interpreted.

Make sure you use the latest server version, latest client version and try one more time.

**Comment by kroyee** [comment]
I just tried to connect 3 clients to a server, it all functions like it should for me.
