### ISSUE TITLE
[UX]Add feature - "X won the previous round"

### ISSUE THREAD

**Issue by kb1900** [kroyee/SpeedBlocks#44]
It is currently hard to tell who won the previous round. In fact when two players are near the top of their field and one wins - its almost impossible to tell which one of them one. 

A simple write to the chat for the room would resolve this. or drawing a graphic on the game field

**Comment by kroyee** [comment]
Yes, I'm thinking I will make the positions drawn on the playfields, like in cultris.
Winner, 2nd, 3rd and so on.
