### ISSUE TITLE
[BUG] Combo Timer not working properly or not drawn properly?

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#45]
Please watch the video and pay attention to the line clears and the combo timer!
https://youtu.be/NmdiDgmpZeQ
I have to say that I am not using the latest build.

**Comment by jefgenowitsch** [comment]
Can anybody explain the creteria when a combo sound is being played?
In the video on combo 5, 8, 11, 13.

**Comment by kroyee** [comment]
It plays a sound on 5, 8, 11, 13, 15, 17, 19, 21.

**Comment by kroyee** [comment]
Your video link is broken btw.

**Comment by jefgenowitsch** [comment]
updated https://youtu.be/NmdiDgmpZeQ
