### ISSUE TITLE
[UX] [DISCUSSION] The cursor should be in the textfield when switching to chat(s)

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#47]
**Steps to reproduce:**

Switch to the room or lobby chat window

**Expected result:**

Instant writing without clicking in the textbox

**Actual Result**

One have to click in the field to type something

Idea: The cursor should be in the textbox when switching to a chat window

**Comment by kroyee** [comment]
Maybe, but you can't have the cursor in the text-box and play at the same time.

What about if pressing Enter focuses the textbox, and then you can type. That way you can switch over to the chat just to read without interrupting your playing but still have an easy way to access the chat without having to use the mouse.

**Comment by jefgenowitsch** [comment]
What about pressing the key for switching to chat places the cursor in the box and pressing it again the cursor is removed and you can play?

**Comment by jefgenowitsch** [comment]
Forget my reply above. Your idea is better!

**Comment by zDEFz** [comment]
@kroyee you could catch all buttons that are NOT controls of the game before you processing it and send it either to the game OR the Textbox at the same time.
That would need some invoking.
You probably would need implement some type of threading for it.

However, your idea is far more easy to implement @kroyee

**Comment by kroyee** [comment]
I made some changes and now it works like the following:

- If you press Return (online, in a room) the game will switch to chat and the chatbox is selected
- If you press Return while the chatbox is empty, the chatbox will be deselected
- If you press Esc the chatbox will be deselected (works even if you have written something)

**Comment by Noir-** [comment]
Does this fix the issue?
