### ISSUE TITLE
[BUG] Multiple equal guest names are possible

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#48]
**Steps to reproduce:**

start multiple games and connect to the server with the same guest name

**Expected result:**
Notification that the name is already taken so that the user has to change it 
or 
automatically adding a counter at the end of the guest name 

**Actual Result**

The same guest name can be used several times, so that distinguishing players is impossible especially in the chat

**Comment by kroyee** [comment]
This is fixed, but you need to update server+client
