### ISSUE TITLE
Re-entering training does not restart the mode after a game over

### ISSUE THREAD

**Issue by chinatsu** [kroyee/SpeedBlocks#5]
Steps to reproduce:
1. Go into training
2. Lose on purpose
3. Exit training mode
4. Enter training mode again

Expected result:
The game mode starts

Actual result:
Game over screen

You can keep exiting the mode and re-enter, it will keep telling you game over. It is possible to play again if `enter` is pressed on the game over screen, as per normal current behaviour.

**Comment by zDEFz** [comment]
+1
