### ISSUE TITLE
[Improvement][UX] Flexible game starting behavior

### ISSUE THREAD

**Issue by Noir-** [kroyee/SpeedBlocks#6]
(Could we have assignable labels like I did with [] somehow?)

We could implement a more flexible game start mechanism which behaves like the following:

1. the game ends
2. countdown of X seconds starts
3. if the user takes a certain action (keyboard or button press), interrupt the countdown and go to 4.
4. the game starts

In multiplayer mode, the countdown would only be interrupted when all active players have taken the specific action.

This would solve the waiting issue when a game quickly ends like in cheese mode or when a player tops out with the initial stack in 1 on 1.

**Comment by zDEFz** [comment]
+1, see TODO

**Comment by kroyee** [comment]
This has been implemented now.
The standard ready button is F5, if all players press F5 the game start imidiately, otherwise it waits X seconds then start automatically.
If X is set to 0 it will wait until all players are ready. This is currently being used in tournament games.
