### ISSUE TITLE
[TN] Ghost user problem

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#61]
Watch the video: https://youtu.be/PrDhoIEQvaM
Apparently the server didn't notice that sicknote got kicked (that's why sicknote's field is empty and sick did relogin). This can bee seen at the beginning of the video.

Furthermore the server doesn't recognize that sick left the game. This is noticable at the beginning of the video. This can bee seen at the end of the video.

**Comment by kroyee** [comment]
Ok, I've seen it do this at times before.
Not sure if it's client or server side, or exactly when/how it happens.
I'll close this issue for now and we can re-open when we have more information.
