### ISSUE TITLE
[UX]Hoover over the playfield of the opponent does enlarge and overlap the adjoined playfield(s)

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#62]
Watch the video: https://youtu.be/I9Nif_ppH04

**Comment by kroyee** [comment]
I see that the enlarging animation is way too slow.
Is this always the case? Otherwise you need to give some more information.

**Comment by jefgenowitsch** [comment]
Yes, it is always the case.

**Comment by kroyee** [comment]
So to be clear here, it SHOULD enlarge the field, and it SHOULD overlap.
The animation should be much faster and smooth though.

**Comment by jefgenowitsch** [comment]
I'm sorry for not being clear at all with this issue:)

Yes, the enlargement of the field is nice and on purpose. That's not what I am wondering about.
But the overlapping...
Wouldn't it be a problem in watching the big transparent playfield which does overlap other playfields, on which the movements of the players are seen?
An idea is that the hoovered/chosen playfield gets untransparent?

**Comment by kroyee** [comment]
I don't think it's a problem.. since the fields are just a little bit transparent.
If it proves to be confusing we could add an additional layer of black behind the playfield to make it more clear.
I'll leave the issue open and we can see.

**Comment by kroyee** [comment]
Or we could simply reduce the transparency as you suggested.

**Comment by jefgenowitsch** [comment]
watch:

https://youtu.be/gmUODQgm1Fk

**Comment by kroyee** [comment]
Yeah, it looks ok to me.
What do you think?

**Comment by kb1900** [comment]
I think slightly less transparency or even complete opacity would be better tbh. i think its just a personal preference though as i see the appeal of transparency

**Comment by jefgenowitsch** [comment]
I'm for complete opacity.

**Comment by zDEFz** [comment]
Maybe implement a simple transparency slider for preview.
Maybe create a new tab name it advanced and put other settings in it.
