### ISSUE TITLE
[BUG]Combo timer still not working properly

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#67]
Reference to #45, #53.
Latest client+server.
Here: https://youtu.be/NtLPgmJEagY

**Comment by kroyee** [comment]
I fail to see what's not working.

**Comment by jefgenowitsch** [comment]
You are talking about the code, right?

**Comment by kroyee** [comment]
I'm talking about the combo timer in your video.
What is it that's not working?

**Comment by jefgenowitsch** [comment]
Why is the combo starting ohne time with a fully filled red circle and sometimes not?

**Comment by kroyee** [comment]
Because you are clearing different amount if lines.
If you remove 1 line, the timer will start ~3/4 if you clear 2 or more lines it will start at full.

**Comment by jefgenowitsch** [comment]
Thanks for clarification:)
