### ISSUE TITLE
[UX][DISCUSSION]A list of players who are online?

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#69]
I would like to have a list which contains all players who are currently online.

**Comment by kroyee** [comment]
This is a good idea. We could put a list of players in the lobby-chat.
Not sure where to put it to make it accessible from within a room though.

**Comment by ghost** [comment]
In the lobby :S

**Comment by jefgenowitsch** [comment]
Is a slide in list from the right that is activated by hoovering over an area at the right possible?

**Comment by kroyee** [comment]
Everything is possible. Not going to spend to much time focusing on the GUI at the moment though.
It **is** a very important part, but also something that takes a lot of time and trying to get it good.

At this point there are too much basic functionality that is still missing. When the game is in a more complete state then hopefully the focus can shift more towards making the GUI better.

**Comment by kroyee** [comment]
The lobby list has been implemented.
