### ISSUE TITLE
[FN] Randomizer starting with Z or S piece

### ISSUE THREAD

**Issue by kb1900** [kroyee/SpeedBlocks#7]
I believe in the end this will be up to the discretion of super but in c2 it is impossible to start any game with a Z or S piece. This is only for the first piece and seems to function in isolation for the rest of the randomizer. 

I am not sure if you would like this implemented in SpeedBlocks, but seeing as its a cultris clone, I thought I would bring it up.

**Comment by kroyee** [comment]
Another detail I've never paid attention to in Cultris. :open_mouth: 

Anyone else has an opinion on this? Seems ok by me. Will put it in if more people throw in some upvotes.

**Comment by kb1900** [comment]
i believe it makes a big deal for the sprint/maserati players who have grown accustomed to just hitting spacebar for their first piece 99% of the time. even in nullpomino i am unsure if you get S or Z in the first piece
