### ISSUE TITLE
[UX] IF player has a high stack and does a soft drop - harddrop / insta drop of next and current piece occurs

### ISSUE THREAD

**Issue by zDEFz** [kroyee/SpeedBlocks#70]
**Steps to reproduce**

1. Do some decent stack
2. Do some sort of Soft drop while your stack is somewhat high

**Expected result**

There are no additional Harddrops ocurring, Stack is controllable and I won't get like an insta death

**Acutal Result**

High stack is not controllable when you soft drop really often.
We saw this also ocurring on many players already.

Here is a frame by Frame Video - First slow and after that some footage of the situation.

https://www.youtube.com/watch?v=YQa6RPQ5qOs
If you need also to know which keys are being held or pressed i could search for a good key sniffer...

Client = latest
Server = latest

**Comment by kb1900** [comment]
Yes. I can confirm this bug. Originally I thought that it was just something to do with lock delay or incoming lines of garbage. but it seems hard to tell exactly what is causing it

**Comment by kroyee** [comment]
I'm not sure I understand what is happening. When I look at the video the speed of the pieces are quite high.
Currently the lock down time is connected to the speed at witch the pieces fall by themselves.
All I can really see is that your stack is high and that your topping out.

**Comment by zDEFz** [comment]
How to explain that ? It seems like if i did the Softdrop there the piece did lock down 1 block to early and i did not assume that it did lock in. So i did press Hard Drop the same time and got a massive amount of insta Hard drops and was already dead.

**Comment by kroyee** [comment]
Ok, from looking at it again, I looks like the blue L is being Hard Dropped, but the pieces after that are just falling normally. Because the falling speed is at max = lockdown time is very low.
Could it be that simple?

**Comment by zDEFz** [comment]
Yes its probably like this but i didn't had control to go left / right after the pieces going into "normal-mode"
It's easier to die on top in this game as in cultris 2
I also played a long Training game so because of this falling speed is current max

**Comment by kroyee** [comment]
Yes, I don't think this will be a big problem as multiplayer does not usually last that long. And if they do my idea was that making it hard to have a high stack by having very fast falling speed would naturally end the game.
A little bit the same way as increased lines sent does now in cultris.

**Comment by kroyee** [comment]
We can also change how long it takes for the falling speed to increase and reach max.

**Comment by zDEFz** [comment]
Wait but it doesn't only has to do only with falling speed.
I already told you the max falling speed is quite slow for me.

If you compare : In Cultris II the max falling speed is almost instant.
And i don't have those multi - instant drop issues.

iirc other people had the same problem. If falling speed is the cause then let us figure that out by forcing it to some slow number.

**Comment by kroyee** [comment]
Ok, so the difference is in how the lock-down time works then probably. In speedblock the lockdown-time is the exact same as the current falling speed.
So when falling speed is high, lock down time will be almost instant.
I could try setting the lockdown time to a fixed value instead.
Gonna go and experiment a little with cultris to see how it works there.

**Comment by kroyee** [comment]
Yeah, from what I can tell this definitely has to do with the lock-down time.
In cultris, even if falling speed is very fast the lockdown time is still close to (or exactly) the same as when the falling speed is slow.

**Comment by kb1900** [comment]
yes @kroyee i think i and other players who softdrop a lot to have a completely **fixed** and static lock time (lock delay). it allows for much more consistent play while receiving lines and playing at low mid and high positions of the matrix
