### ISSUE TITLE
[UX] graphical issues with room name text

### ISSUE THREAD

**Issue by kb1900** [kroyee/SpeedBlocks#78]
-Create enough rooms such that scroll bar is required
-Scrolling down yields this distortion of the text: https://puu.sh/v0vUh/42d0f14905.png

ALSO

-After test1 room closes, the text is overlayed over the previous text: https://puu.sh/v0vVc/659f8ddddb.png

AND FINALLY

-test2 and test3 rooms close properly after some time but they remain as displayed graphically (same as above screenshot number 2)

**Comment by zDEFz** [comment]
![image](https://cloud.githubusercontent.com/assets/24463722/24380261/c70c01b2-134a-11e7-9803-5cf650771bb5.png)

**Comment by kroyee** [comment]
I found the cause for this earlier today. Had missed 1 break; statement witch was causing things to go bananans.
Have not made any new mac build yet though.
