### ISSUE TITLE
[Discussion][UX] How to handle updates for beta testers?

### ISSUE THREAD

**Issue by Noir-** [kroyee/SpeedBlocks#79]
Seems that we finally get a beta #75 
I guess we need to fix a ton of things as soon as there are more testers. I also assume that we want to reduce bug reports with issues that are already fixed to a minimum to save time and to provide better user experience.
So this leads me to the question: How do we want to handle the updates for the testers? The simplest way I can imagine is displaying a link to the GitHub releases page when a certain flag (Maybe a simple build number via HTTP-GET request?) is set somewhere. This flag should be polled from some server I guess and needs to be set manually or automatically.
I could do that version server stuff in little time with a dumb UI for updating the flag to a new version. In the near future I suggest that we finally dump this stuff into a automated build system which also does the version number updating via post-build script or such.

**Comment by kb1900** [comment]
also bug report entries in the interim shouhld report what machine os and client version the user is using

**Comment by Noir-** [comment]
That's a good point. Client version is easy, OS version depends on the granularity we want. But I'm pretty sure that there are enough examples for this on the net to get some basic meta data. If this is ok for @kroyee I'd start implementing this on the server side.

**Comment by kroyee** [comment]
Yes, go ahead.
It's probably good to distinguish between major versions like Win7, Win8, Win10.
OS X 10.8, 10.9, 10.12 ect.
For the linux/unix systems it gets a bit more unclear.

**Comment by kroyee** [comment]
I did throw up the first release on the relase page already!
So if you make changes to the server, please keep it backward compatible with the set-up that was there. :smile: 

Hope my "just do it" ways is not causing any problems...

**Comment by Noir-** [comment]
Uh ok then the first thin I'm going to do is adding authentication for the user interface to protect the contact information. I'll message you somehow. Maybe on Harddrop.

>For the linux/unix systems it gets a bit more unclear.

I guess the output of `uname -a` would be a helpful for the beginning.

**Comment by Noir-** [comment]
The new fields and authentication are live. Now a API key is required to pull the data while submitting is still possible without authentication.
@kroyee You also got a private message on harddrop.com.
