### ISSUE TITLE
[Discussion] [Bug Reports] Proper fitting to resolution

### ISSUE THREAD

**Issue by zDEFz** [kroyee/SpeedBlocks#81]
Hi,

high res user can not properly use the application or have other Problems.

**_Landscape Ultra Mega Wide rofl_**

![image](https://cloud.githubusercontent.com/assets/24463722/24484698/e3cee100-14ff-11e7-8177-63cc5fa80b54.png)

**Examples are distorted Games.**
Portrait Mode

**Missing Text / Messages general weird**
https://i.imgur.com/bQ3XKuJ.jpg
https://i.imgur.com/f42FlKp.jpg
https://i.imgur.com/l6zd70p.jpg
https://i.imgur.com/HmeBvI3.jpg
https://i.imgur.com/VPn279O.jpg

![image](https://cloud.githubusercontent.com/assets/24463722/24484600/51332680-14ff-11e7-861b-1875fb7c585b.png)
![image](https://cloud.githubusercontent.com/assets/24463722/24484603/543018e8-14ff-11e7-8767-7fa4fec1e851.png)
![image](https://cloud.githubusercontent.com/assets/24463722/24484606/57129022-14ff-11e7-8d7e-dcd6aed7b2b9.png)

![image](https://cloud.githubusercontent.com/assets/24463722/24484608/5959853e-14ff-11e7-82da-98e55c0b4384.png)
![image](https://cloud.githubusercontent.com/assets/24463722/24484613/5fad5e60-14ff-11e7-82a3-6c1fdf35793c.png)
![image](https://cloud.githubusercontent.com/assets/24463722/24484615/6287bf40-14ff-11e7-9355-9c27b4ad0ed5.png)

Game does stay 4:3 and also not aligned to Portrait but
 then having weird GUI Problems lol

**Comment by kroyee** [comment]
The missing text issues are from the bug mentioned in the readme with TGUI. If you build the latest TGUI yourself that problem will go away (he is releasing the next stable 0.7.4 in some weeks).
As for a multi-monitor setup SFML does not support this is general. Sorry about that.

**Comment by zDEFz** [comment]
If we could scale playfield it would be much easier at least in Full screen mode.
It would be nice if it would be scalable like a normal window.
