### ISSUE TITLE
[UX][Fine Tuning]Infinite play possible?

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#89]
Ok I have been playing alone in ffa for a while and I believe I could survive for a very long (infinite) time. Maybe the drop speed should be fine tuned, if this behaviour isn't desired.
![speed 2017-04-05 20-32-46-673](https://cloud.githubusercontent.com/assets/803239/24721173/f4635274-1a2e-11e7-9c37-74475155949b.jpg)

**Comment by kroyee** [comment]
I can confirm that currently the drop speed will max out after a few minutes of play. After that it does not get any faster.
Any opinions on what would be the best setup for this?

**Comment by jefgenowitsch** [comment]
My idea is (which has to be tested) increase the speed by steps and leave the speed for a certain amount of time.
1. If three players do play do 10 after idk 3 min.
2. If only two players do play do 10 after idk 2,5 min.
If 1 then 2 do 10 after 3 min.
10. Naive explanation: increase 3bpm for 20 sec. then 6 bpm for 20 sec. then 9 bpm for 20 sec.
That is just a pattern without any realistic speed or time sequence....

**Comment by kroyee** [comment]
Currently it works like this:
- When a new game starts it take 1 second for the piece to move down 1 step.
- Every 3 seconds that time is reduced by 10ms. (starts at 1000, after 3 sec 990, after 6 sec 980 ect).
- When it reaches 100 it does not go any lower.

**Comment by jefgenowitsch** [comment]
Really strange! The number "3." is wrong, I had it changed to 10. (https://www.youtube.com/watch?v=V6VGG01vF-s)

Why not when it reaches X=100ms test:
1. If three players do play for 2 min, then X-20 ms? after 2 min of playtime again X-20 ms......again...again.....

Y=X or Y=80ms (idk what is good)
2. If only two players do play for 90 sec, then Y-20 ms? after 2 min of playtime again Y-20 ms......again...again.....

Z=X or Z=60ms
3. If playing alone: after 75 sec, then Z-20 ms? after 2 min of playtime again Z-20 ms......again...again.....

I guess the parameters aren't realistic...but maybe my idea is now a bit clearer :D
