### ISSUE TITLE
[UX] Holes in the garbage lines too easy?

### ISSUE THREAD

**Issue by jefgenowitsch** [kroyee/SpeedBlocks#91]
Is this coincidence or could the holes in the lines be more fine tuned, e. g. made more random and more away from each other. The holes in the screenshot seem to be mirrored and slightly changed.

![speed 2017-04-11 17-29-02-044](https://cloud.githubusercontent.com/assets/803239/24917269/29f9e0c8-1ecc-11e7-8cac-8f8aa5b9de32.jpg)

**Comment by kroyee** [comment]
It currently uses a Mersenne Twister 19937 generator with a standard distribution between 0-9 to make the holes at random.
The Mersenne Twister is a more advanced randomness algorithm that passes [statistical randomness tests](https://en.wikipedia.org/wiki/Mersenne_Twister#Advantages) and I don't think it can get more random then this.

You could do a weighted randomness, to make it less likely for holes to be close to each other, but that would strictly speaking be less random.

Also another thing to note is that just like the sequence of pieces that every player will get is the same, the sequence of holes in the garbage will also be the same for all players.

**Comment by ghost** [comment]
tbh, it's not that easy to downstack this garbage... at times.

**Comment by jefgenowitsch** [comment]
Good to know, thx!
